services:
  onlineide:
    container_name: server
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
    - 8080
    healthcheck:
      interval: 1m30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080
      timeout: 10s
    image: oven/bun
    ports:
    - '50004'
    user: '1000'
    volumes:
    - /home/ubuntu/OnlineIDE/:/home/container/
    working_dir: /home/container
    command: bun .
version: '3'