services:
  onlineide:
    container_name: server
    restart: always
    healthcheck:
      interval: 1m30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080
      timeout: 10s
    image: oven/bun
    user: '1000'
    volumes:
      - /home/ubuntu/OnlineIDE/:/home/container/
    working_dir: /home/container
    command: bun .
    ports:
      - "50004:8080"
    depends_on:
      - api
    stop_grace_period: 1s
  api:
    image: piston
    container_name: piston_api
    restart: always
    privileged: true
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec
    environment:
      PISTON_RUN_TIMEOUT: 600000
      PISTON_COMPILE_MEMORY_LIMIT: 400000000
      PISTON_RUN_MEMORY_LIMIT: 400000000
      PISTON_BIND_ADDRESS: 0.0.0.0:2000